document           = *line
line               = *indent (paragraph / term / instruction) eol
term               = "-" name [":" *mark [categorizer] ["=" expr] ]
name               = 1*(ALPHA / " ")
paragraph          = begin-paragraph *text
begin-paragraph    = %x21-2c / %x2e-ff                                   ; everything except " " and "-"
text               = %x20-ff
indent             = "    "
expr               = grouped / simple-expr
grouped            = "(" expr ")"
simple-expr        = (number / str / function-call / name)
instruction        = definition / if / loop