#! /usr/bin/python
import os, sys

def is_root(folder):
    return bool(        
        os.path.isdir(os.path.join(folder, 'test')))

def find_root():
    folder = os.path.dirname(os.path.abspath(__file__))
    while True:
        if is_root(folder):
            return folder
        assert folder
        folder, child = os.path.split(folder)

def find_testrunners(root):
    testrunners = []
    test_folder = os.path.join(root, 'test')
    items = os.listdir(test_folder)
    for item in items:
        if os.path.isdir(os.path.join(root, 'build')):
            if os.path.isfile(os.path.join(test_folder, item, 'sconscript')):
                testrunners.append(item)
        else:
            if os.path.isfile(os.path.join(test_folder, item, 'testrunner')):
                testrunners.append(item)
    return testrunners

def run_testrunners():
    exit_code = 0
    root = find_root()
    testrunners = find_testrunners(root)
    for tr in testrunners:
        if os.path.isdir(os.path.join(root, 'build')):
            path = os.path.join(root, 'build', 'test', tr, 'testrunner')
            report_path = os.path.join(root, 'build', 'test', tr, 'test_results.xml')
        else:
            path = os.path.join(root, 'test', tr, 'testrunner')
            report_path = os.path.join(root, 'test', tr, 'test_results.xml')
        result = os.system('%s --gtest_output=xml:%s' % (path, report_path))
        if result:
            exit_code += 1
        print('')
    if exit_code:
        print('FAIL: at least %d tests did not pass.\n' % exit_code)
    else:
        print('All %d testrunners reported SUCCESS.\n' % len(testrunners))
    sys.exit(exit_code) 

if __name__ == '__main__':
    run_testrunners()
