#!/usr/bin/env python

if __name__ == '__main__':
    import sys, sanitizers
    compiler = 'clang++'
    if len(sys.argv) == 2:
        compiler = sys.argv[1]
    print ' '.join(sanitizers.detect(compiler))

