#! /usr/bin/env python
import os, sys, subprocess, shutil
import sanitizers

def x(cmd):
    print(cmd)
    subprocess.check_call(cmd.split(' '))

def install_required_tools():
    travis_os = os.getenv('TRAVIS_OS_NAME')
    if travis_os == 'linux':
        x('sudo apt-get remove libboost-*-dev -y')
        x('sudo apt-get autoremove -y')
        x('sudo add-apt-repository ppa:boost-latest/ppa -y')
        x('sudo apt-get update -qq')
        x('sudo apt-get install -y libboost1.55-all-dev')
        x('sudo apt-get install -y libpcre3-dev')
        x('sudo apt-get install -y doxygen graphviz')
    elif travis_os == 'osx':
        x('brew install cmake')
        x('brew install boost')
        x('brew install pcre')
        x('brew install doxygen')
        x('brew install graphviz')

if __name__ == '__main__':
    install_required_tools()
    non_build_variants = 'integer undefined unsigned-integer-overflow address'.split(' ')
    build_variants = ['Debug', 'Release', 'analyze'] + ['sanitize-' + s for s in sanitizers.detect() 
        if s not in non_build_variants]
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
    old_cwd = os.getcwd()
    for variant in build_variants: 
        print('\n---------------------------------- %s build ------' % variant)
        folder = 'build/travis-%s' % variant
        if os.path.isdir(folder):
            shutil.rmtree(folder)
        os.makedirs(folder)
        os.chdir(folder)
        try:
            x('cmake -DCMAKE_BUILD_TYPE=%s ../..' % variant)
            x('make')
            x('make test')
            if variant == 'Release':
                 x('make package')
                 x('make doc')
        finally:
            os.chdir(old_cwd)
