
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xe8\x05\xe1\xf6\xa6\xbb\xca\xff"\xcc\xd5\x06u7-A'
    
_lr_action_items = {'STAR':([1,2,3,4,15,16,17,18,19,20,21,22,23,24,],[5,-13,-12,10,-9,-7,-10,-11,-8,5,5,5,5,5,]),'NUMBER':([0,5,6,7,8,9,10,11,12,13,14,],[2,2,2,2,2,2,2,2,2,2,2,]),'PLUS':([1,2,3,4,15,16,17,18,19,20,21,22,23,24,],[6,-13,-12,11,-9,-7,-10,-11,-8,6,6,6,6,6,]),'SLASH':([1,2,3,4,15,16,17,18,19,20,21,22,23,24,],[7,-13,-12,12,-9,-7,-10,-11,-8,7,7,7,7,7,]),'MODULO':([1,2,3,4,15,16,17,18,19,20,21,22,23,24,],[8,-13,-12,13,-9,-7,-10,-11,-8,8,8,8,8,8,]),'MINUS':([1,2,3,4,15,16,17,18,19,20,21,22,23,24,],[9,-13,-12,14,-9,-7,-10,-11,-8,9,9,9,9,9,]),'$end':([1,2,3,4,15,16,17,18,19,20,21,22,23,24,],[-6,-13,-12,0,-9,-7,-10,-11,-8,-3,-1,-4,-5,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,10,11,12,13,14,],[1,20,21,22,23,24,]),'expression':([0,],[4,]),'factor':([0,5,6,7,8,9,10,11,12,13,14,],[3,15,16,17,18,19,3,3,3,3,3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression','parser.py',6),
  ('expression -> expression MINUS term','expression',3,'p_expression','parser.py',7),
  ('expression -> expression STAR term','expression',3,'p_expression','parser.py',8),
  ('expression -> expression SLASH term','expression',3,'p_expression','parser.py',9),
  ('expression -> expression MODULO term','expression',3,'p_expression','parser.py',10),
  ('expression -> term','expression',1,'p_expression','parser.py',11),
  ('term -> term PLUS factor','term',3,'p_term','parser.py',15),
  ('term -> term MINUS factor','term',3,'p_term','parser.py',16),
  ('term -> term STAR factor','term',3,'p_term','parser.py',17),
  ('term -> term SLASH factor','term',3,'p_term','parser.py',18),
  ('term -> term MODULO factor','term',3,'p_term','parser.py',19),
  ('term -> factor','term',1,'p_term_factor','parser.py',23),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',27),
]
